### ISSUE TITLE
Error with the publisher dependeces  

### ISSUE THREAD

**Issue by Edipo3098** [kiwicampus/2D-Test-Track-Planner#1]
When i made the two first python points and start the subscribers the system throw and error, is like if the topic don't have any info from the publisher

**Comment by JohnBetaCode** [comment]
Please which points are you doing and could you provide logs description or image if we can reproduce the error or see what's happening

**Comment by Edipo3098** [comment]
I'm doing the first to points, (Implement/Create the path planner status subscriber -Implement/Create the Kiwibot status subscriber) and in the image you can see the implementation
![image](https://user-images.githubusercontent.com/45560069/116590808-ccaf1180-a8e3-11eb-974b-96a959095aad.png)
When i run the program i'm getting  this error 
(  [ERROR][NODE_VISUAL_GUI][RUN]: 'Subscription' object has no attribute 'land_marks', <class 'AttributeError'>, node_visual_gui.py, 439 )
When i do a echo into the topics i got, so it looks like nothings is on the topic
![image](https://user-images.githubusercontent.com/45560069/116591221-316a6c00-a8e4-11eb-96f5-b6894a04ac98.png)

**Comment by JohnBetaCode** [comment]
did you source ros2 installation path and the setup.bash in the planner/ros2/install folder, otherwise ros2 doesn't know the context of your project, and so messages, services, topics, etc .... This a basic ros1/ros2 concept.

**Comment by JohnBetaCode** [comment]
One point of the extra-homework is to make this. I'm gonna close the issue. if you get more problems related to, please re-open it

**Comment by Edipo3098** [comment]
Yes i'm having issues because i already did the source getting the same error 
![image](https://user-images.githubusercontent.com/45560069/116613936-e3169680-a8fe-11eb-9e5f-c07d86516067.png)
And i made the proof looking the info regarding the node, you can see that i can get the info of the node that means that ros2 already know about that node but can't get the info of the topic thas why the node visual_node can't work because there is no information in the topic 
![image](https://user-images.githubusercontent.com/45560069/116614006-faee1a80-a8fe-11eb-9b65-b0bcfe99095e.png)

**Comment by dadaroce** [comment]
`[ERROR][NODE_VISUAL_GUI][RUN]: 'Subscription' object has no attribute 'land_marks', <class 'AttributeError'>, node_visual_gui.py, 439 `, could you provide full logs? or push your code so I could check it.

@Edipo3098

**Comment by Edipo3098** [comment]
I already push the code on the develop branch the only thing that i change is the node visual_node

**Comment by Edipo3098** [comment]
I already push the code on the develop branch the only thing that i change is the node visual_node

**Comment by Edipo3098** [comment]
Already solved

**Comment by dadaroce** [comment]
@Edipo3098 
I've checked and you're overriding the message variable, and it's not suppose to do that. 

These two variables are being overriding:
[self.msg_planner](https://github.com/Edipo3098/2D-Test-Track-Planner/blob/develop/planner/ros2/src/graphics/graphics/node_visual_gui.py#L88)

[self.msg_kiwibot](https://github.com/Edipo3098/2D-Test-Track-Planner/blob/develop/planner/ros2/src/graphics/graphics/node_visual_gui.py#L100)

So, you are trying to use a "subscriber" object as a "message" object. That's why you're getting that log. Please review your code, check [this example](https://docs.ros.org/en/foxy/Tutorials/Writing-A-Simple-Py-Publisher-And-Subscriber.html#write-the-publisher-node). There is a variable called `msg = String()` whose basically is assigned as a message-type variable and it has a attribute `data`. So, what happen if you override that `msg` variable to another type before try to use `data` attribute?

```.py
msg = String()
self.create_publisher(String, 'topic', 10)
msg.data = 'Hello World: %d' % self.i
````
An error will raise up.
In the same way you're overriding these two [self.msg_planner](https://github.com/Edipo3098/2D-Test-Track-Planner/blob/develop/planner/ros2/src/graphics/graphics/node_visual_gui.py#L88) and [self.msg_kiwibot](https://github.com/Edipo3098/2D-Test-Track-Planner/blob/develop/planner/ros2/src/graphics/graphics/node_visual_gui.py#L100). Please don't touch those two variables
```.py
self.msg_planner = planner_msg()
self.msg_kiwibot = kiwibot_msg()
```
Call your subscriber as you want, but not override them.

This is your first Strike 👎🏽  you've two left don't waste them 😿.
As this isn't a real issue about the code or our mistake, you will not get extra point, let me know if everything is clear to close the issue.

**Comment by dadaroce** [comment]
> Already solved

Sorry for my late response, it's great that you've solve it by your own. 😸
